[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn spss_online.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
