# Generated by Django 6.0.4 on 2026-04-12 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/')),
                ('file_type', models.CharField(default='csv', max_length=20)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('column_info', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('histogram', 'Histogram'), ('scatter', 'Scatter Plot'), ('box', 'Box Plot'), ('line', 'Line Chart'), ('pie', 'Pie Chart')], max_length=30)),
                ('parameters', models.TextField(default='{}')),
                ('chart_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='core.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('descriptive', 'Deskriptif'), ('frequencies', 'Frekuensi'), ('crosstab', 'Crosstab'), ('ttest_independent', 'T-Test Independen'), ('ttest_onesample', 'T-Test 1 Sampel'), ('ttest_paired', 'T-Test Berpasangan'), ('anova_oneway', 'ANOVA Satu Arah'), ('anova_twoway', 'ANOVA Dua Arah'), ('manova', 'MANOVA'), ('correlation_pearson', 'Korelasi Pearson'), ('correlation_spearman', 'Korelasi Spearman'), ('regression_linear', 'Regresi Linear'), ('regression_logistic', 'Regresi Logistik'), ('normality', 'Uji Normalitas'), ('chi_square', 'Chi-Square'), ('mann_whitney', 'Mann-Whitney U'), ('wilcoxon', 'Wilcoxon'), ('kruskal_wallis', 'Kruskal-Wallis'), ('factor', 'Analisis Faktor'), ('cluster', 'Analisis Klaster'), ('reliability', 'Reliabilitas (Alpha)')], max_length=50)),
                ('parameters', models.TextField(default='{}')),
                ('output_html', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
